# Generated by Django 3.2.12 on 2022-03-17 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='likedrecipe',
            name='recipe_seq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='dislikedingredient',
            name='ingredient_seq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient'),
        ),
        migrations.AddField(
            model_name='dislikedingredient',
            name='member_seq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='member',
            name='disliked_ingredients',
            field=models.ManyToManyField(related_name='members', through='members.DislikedIngredient', to='recipes.Ingredient'),
        ),
        migrations.AddField(
            model_name='member',
            name='liked_recipes',
            field=models.ManyToManyField(related_name='members', through='members.LikedRecipe', to='recipes.Recipe'),
        ),
    ]
