# Generated by Django 3.2.12 on 2022-03-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_member_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='google_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
