# Generated by Django 3.2.12 on 2022-03-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20220314_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='kakao_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
