# Generated by Django 3.2.12 on 2022-03-17 15:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('allergy_seq', models.IntegerField(primary_key=True, serialize=False)),
                ('allergy_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tb_allergy',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_seq', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tb_category',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredient_seq', models.IntegerField(primary_key=True, serialize=False)),
                ('ingredient_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tb_ingredient',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('keyword_seq', models.IntegerField(primary_key=True, serialize=False)),
                ('keyword_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tb_keyword',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_seq', models.AutoField(primary_key=True, serialize=False)),
                ('recipe_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('cook_time', models.IntegerField()),
                ('prep_time', models.IntegerField()),
                ('total_time', models.IntegerField()),
                ('ingredient_raw', models.TextField()),
                ('serving_size', models.CharField(max_length=255)),
                ('servings', models.FloatField()),
                ('calories', models.FloatField()),
                ('fat_content', models.FloatField()),
                ('saturated_fat_content', models.FloatField()),
                ('cholesterol_content', models.FloatField()),
                ('sodium_content', models.FloatField()),
                ('carbohydrate_content', models.FloatField()),
                ('fiber_content', models.FloatField()),
                ('sugar_content', models.FloatField()),
                ('protein_content', models.FloatField()),
                ('instructions', models.TextField()),
                ('images', models.TextField()),
            ],
            options={
                'db_table': 'tb_recipe',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image_url', models.CharField(max_length=255)),
                ('ratings', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('create_date', models.DateTimeField(null=True)),
                ('last_modified_date', models.DateTimeField(null=True)),
                ('member_seq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recipe_seq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
            options={
                'db_table': 'tb_review',
            },
        ),
        migrations.CreateModel(
            name='RecipeKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_seq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.keyword')),
                ('recipe_seq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
            options={
                'db_table': 'tb_recipe_keyword',
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_seq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient')),
                ('recipe_seq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
            options={
                'db_table': 'tb_recipe_ingredient',
            },
        ),
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_seq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.category')),
                ('recipe_seq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
            options={
                'db_table': 'tb_recipe_category',
            },
        ),
        migrations.CreateModel(
            name='RecipeAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy_seq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.allergy')),
                ('recipe_seq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
            options={
                'db_table': 'tb_recipe_allergy',
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='allergies',
            field=models.ManyToManyField(related_name='recipes', through='recipes.RecipeAllergy', to='recipes.Allergy'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='categories',
            field=models.ManyToManyField(related_name='recipes', through='recipes.RecipeCategory', to='recipes.Category'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='recipes.RecipeIngredient', to='recipes.Ingredient'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='keywords',
            field=models.ManyToManyField(related_name='recipes', through='recipes.RecipeKeyword', to='recipes.Keyword'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='reviews',
            field=models.ManyToManyField(through='recipes.Review', to=settings.AUTH_USER_MODEL),
        ),
    ]
